language: python
before_install:
  - pip install codecov
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov .
script: py.test --cov=./
sudo: false
after_success:
  - codecov
